services:
  test_db:
    container_name: test_db
    image: "wiktorn/overpass-api:0.7.62"
    volumes:
      - "./test_db:/db"
    ports:
      - "8081:80"
    environment:
      OVERPASS_MODE: init
      OVERPASS_PLANET_URL: "https://download.geofabrik.de/north-america/us/washington-latest.osm.pbf"
      OVERPASS_PLANET_PREPROCESS: "mv /db/planet.osm.bz2 /db/planet.osm.pbf && osmium cat -o /db/planet.osm.bz2 /db/planet.osm.pbf && rm /db/planet.osm.pbf"
